# Generated by Django 5.0.7 on 2024-07-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_ID',
            field=models.CharField(default='101', max_length=3, primary_key=True, serialize=False),
        ),
    ]
