# Generated by Django 5.0.7 on 2024-07-19 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JdGood",
            fields=[
                (
                    "acid",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "detail_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("image_link", models.CharField(blank=True, max_length=255, null=True)),
                ("comment_count", models.IntegerField(blank=True, null=True)),
                ("shop", models.CharField(blank=True, max_length=255, null=True)),
                ("shop_link", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "JD 商品",
                "verbose_name_plural": "JD 商品",
                "db_table": "jd_goods",
            },
        ),
        migrations.CreateModel(
            name="JdComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("date", models.DateTimeField()),
                ("good_id", models.CharField(max_length=50)),
                ("good_name", models.CharField(max_length=255, null=True)),
                (
                    "comment_tags",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reply_count", models.IntegerField(default=0)),
                ("score", models.IntegerField()),
                ("user_level_id", models.IntegerField()),
                (
                    "user_province",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=50)),
                ("score1", models.IntegerField(default=0)),
                ("score2", models.IntegerField(default=0)),
                ("score3", models.IntegerField(default=0)),
                ("score4", models.IntegerField(default=0)),
                ("score5", models.IntegerField(default=0)),
                (
                    "good_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shows.jdgood"
                    ),
                ),
            ],
            options={
                "verbose_name": "JD Comment",
                "verbose_name_plural": "JD Comments",
                "db_table": "jd_comments",
            },
        ),
    ]
