# Generated by Django 5.0.7 on 2024-07-15 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JdGood",
            fields=[
                (
                    "acid",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                ("shop_name", models.CharField(default="未知商店", max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("operation", models.CharField(default="未知操作", max_length=255)),
                ("level", models.CharField(default="未知等级", max_length=50)),
                ("frequency", models.CharField(default="未知频率", max_length=50)),
                ("purify", models.CharField(default="无", max_length=50, null=True)),
                ("type", models.CharField(default="未知类型", max_length=50)),
                ("cwtype", models.CharField(default="未知类型", max_length=50)),
                ("horse", models.CharField(default="未知马力", max_length=50)),
                ("good_func", models.CharField(default="无", max_length=255, null=True)),
                (
                    "apply_space",
                    models.CharField(default="未知空间", max_length=50, null=True),
                ),
                ("featured", models.CharField(default="无", max_length=50, null=True)),
                ("statu", models.CharField(default="未知条件", max_length=50, null=True)),
                (
                    "set_type",
                    models.CharField(default="未知类型", max_length=50, null=True),
                ),
                (
                    "apply_house",
                    models.CharField(default="未知", max_length=50, null=True),
                ),
                (
                    "duct_form",
                    models.CharField(default="未知形式", max_length=50, null=True),
                ),
                ("brand", models.CharField(default="未知品牌", max_length=255)),
                (
                    "wind_position",
                    models.CharField(default="未知", max_length=50, null=True),
                ),
                (
                    "no_drainage",
                    models.CharField(default="未知", max_length=50, null=True),
                ),
                (
                    "min_height",
                    models.CharField(default="未知", max_length=50, null=True),
                ),
                ("cost", models.CharField(default="未知", max_length=50, null=True)),
                (
                    "user_preference",
                    models.CharField(default="未知", max_length=50, null=True),
                ),
                ("comment_count_str", models.CharField(max_length=50)),
                ("average_score", models.FloatField(default=0.0)),
                ("good_count_str", models.CharField(max_length=50)),
                ("general_count_str", models.CharField(max_length=50)),
                ("poor_count_str", models.CharField(max_length=50)),
                ("good_rate", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "JD Good",
                "verbose_name_plural": "JD Goods",
                "db_table": "jd_goods",
            },
        ),
        migrations.CreateModel(
            name="JdComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("date", models.DateTimeField()),
                ("good_id", models.CharField(max_length=50)),
                ("good_name", models.CharField(max_length=255, null=True)),
                (
                    "comment_tags",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reply_count", models.IntegerField(default=0)),
                ("score", models.IntegerField()),
                ("user_level_id", models.IntegerField()),
                (
                    "user_province",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=50)),
                ("score1", models.IntegerField(default=0)),
                ("score2", models.IntegerField(default=0)),
                ("score3", models.IntegerField(default=0)),
                ("score4", models.IntegerField(default=0)),
                ("score5", models.IntegerField(default=0)),
                (
                    "good_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shows.jdgood"
                    ),
                ),
            ],
            options={
                "verbose_name": "JD Comment",
                "verbose_name_plural": "JD Comments",
                "db_table": "jd_comments",
            },
        ),
    ]
